<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Views\Email\ResetPassword.txt" />
    <Content Include="Views\Email\VerifyEmail.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="9.4.1" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.4.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Hangfire" Version="1.8.21" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.12" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Razor.Templating.Core" Version="2.1.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PawPoint.Common\PawPoint.Common.csproj" />
    <ProjectReference Include="..\PawPoint.DB\PawPoint.DB.csproj" />
    <ProjectReference Include="..\PawPoint.ServiceDefaults\PawPoint.ServiceDefaults.csproj" />
    <ProjectReference Include="..\PawPoint.Services\PawPoint.Services.csproj" />
    <ProjectReference Include="..\PawPoint.Common\PawPoint.Common.csproj" />
    <ProjectReference Include="..\PawPoint.DB\PawPoint.DB.csproj" />
    <ProjectReference Include="..\PawPoint.ServiceDefaults\PawPoint.ServiceDefaults.csproj" />
    <ProjectReference Include="..\PawPoint.Services\PawPoint.Services.csproj" />
  </ItemGroup>


	<ProjectExtensions><VisualStudio><UserProperties appsettings_1development_1json__JsonSchema="obj\Debug\net9.0\appsettingsschema.json" /></VisualStudio></ProjectExtensions>

</Project>
